# Generated by Django 4.2.6 on 2023-10-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_followescount"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FollowesCount",
            new_name="FollowersCount",
        ),
    ]
